### ISSUE TITLE
Error reading tracepoint in process monitoring mode

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#113]
```
$ lo2s ~/FIRESTARTER -t 1
[75201006880705][pid: 4077][tid: 22720171465600][ERROR]: Couldn't read information for tracepoint event 1: Failed to read tracepoint ID file /sys/kernel/debug/tracing/events/1/id: No such file or directory
```

**Comment by tilsche** [comment]
In process monitoring mode, access to debugfs should not be *required* (hence it should not be an error).

**Comment by cvonelm** [comment]
This happens because boost::program_options is consuming the -t which belongs to the firestarter call. I've browsed the documentation of boost::program_options if there is some way to make our desired behaviour more clear to the command options parser but nothing feasible turned up so that is most likely wontfix

`
lo2s -- ~/FIRESTARTER -t 1
`

should work though

**Comment by tilsche** [comment]
oops, I should know that better....
