### ISSUE TITLE
Print alternative events when default is not available

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#134]
print alternative events when default ("instructions") is/seems not available. Current output:

```
[29993381748090][pid: 23291][tid: 139717931222848][ERROR]: requested sampling event 'instructions' is not available!
```

@rschoene What are the alternatives? `cpu-cycles`, `ref-cycles`, ...?

**Comment by bmario** [comment]
Extracted from #133

**Comment by cvonelm** [comment]
I somewhat digress here. Our current default metric event is `cpu-clock` which has been in the kernel since the first perf "release" and from looking into the kernel source there is no case where `cpu-clock` fails where other events like `instructions` or `cpu-cycles` wouldn't fail.[1][2]. Which makes sense because the underlying mechanism for `cpu-clock` (`hrtimer`'s) is available universally.

But I generally support the motion to look into perf error reporting in lo2s because it is honestly all over the place and there are a lot of "obvious" misconfigurations we could detect (e.g. wrong `perf_event_paranoid` like in this case)

[1] `PERF_RECORD_BRANCH_SAMPLING` is the sole `perf_event_attr` option not supported by `cpu-clock` (and likely all other software events), but we don't support that in lo2s anyway
[2] There seems to be no difference between software and hardware events for metrics, as there are apparently no hardware mechanisms like PEBS for that case

**Comment by rschoene** [comment]
@cvonelm 
I don't know whether we are on the same page here. I talk about the sampling event, where the default is `instructions` and you talk about metric events. You are right that cpu-clock is universal (and also works in VMs).
@bmario *What are the alternatives? cpu-cycles, ref-cycles, ...?*
`lo2s list-events` says:
```

```List of predefined events:

  (none available)


List of Kernel PMU events:

  cpu/branch-instructions/
  cpu/branch-misses/
  cpu/bus-cycles/
  cpu/cache-misses/
  cpu/cache-references/
  cpu/cpu-cycles/
  cpu/instructions/
  cpu/mem-loads/
  cpu/mem-stores/
  cpu/ref-cycles/
  cpu/topdown-fetch-bubbles/
  cpu/topdown-recovery-bubbles/
  cpu/topdown-slots-issued/
  cpu/topdown-slots-retired/
  cpu/topdown-total-slots/
  cstate_core/c3-residency/
  cstate_core/c6-residency/
  cstate_core/c7-residency/
...
```
However, none of them should work with `perf_event_paranoid` being 3.

**Comment by bmario** [comment]
Should we just using `cpu/instructions/` instead per default? I'm guessing it is the same event but more available?

**Comment by rschoene** [comment]
Maybe task-clocks or cpu-clocks, which is also available in a virtual machine environment

**Comment by bmario** [comment]
Closed. Replaced by #141 and #142.
