### ISSUE TITLE
Find out whether in virtual environment and act accordingly

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#141]
It'd be nice, if `lo2s` would check for the hypervisor flag in `/proc/cpuinfo`. if it finds this flag, it could "warn" the user and automatically choose cpu-clock as the sampling event.

**Comment by bmario** [comment]
Should we also adopt the `count` in that case?

**Comment by bmario** [comment]
For future reference, in a discussion, we acknowledged that technically the sampling period is different when switching to `cpu-clock` as sampling event. `cpu-clock` is denoted in nanoseconds, so the sampling period is roughly twice as long, but that isn't a big issue because running in a virtual environment also has a performance penalty attached to it.
