### ISSUE TITLE
Visual Clarity in Vampir

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/lo2s#190]
Currently sampled CPUs show up as "samples for cpu 22:23" in Vampir while we only write "sample for cpu 22" into the trace.

Figure out where this extraneous ":23" comes from and how we can get rid of it.

**Comment by bmario** [comment]
Vampir is doing that. Vampir needs to "fix" that.

**Comment by tilsche** [comment]
> Vampir is doing that. Vampir needs to "fix" that.

That's not wrong. But the idea of this issue was to figure out more precisely why and what those number might represent.

We keep this open until we know the detail and have a corresponding Vampir issue.

**Comment by bertwesarg** [comment]
This number is the ID of the `LocationGroup` of the `Location`. The reason comes from the fact, that Score-P does not provide unique location names across all locations, thus there are multiple location names like `OpenMP thread 0`, or `Pthread 0` and so on. To be able to distinguished these in Vampir, we add the location group ID to the name. As this is highly producer specific, I would propose to use a trace property to indicate whether the location names are already unique. This property could be set by Lo2s but not by Score-P.

**Comment by tilsche** [comment]
This is now handled in Vampir. It will not show the disambiguation if the names are unique.
