### ISSUE TITLE
Disable --clockid / --list-clockids options if built without USE_PERF_CLOCKID

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#27]
If USE_PERF_CLOCKID==OFF, any execution of `lo2s` (regardless of arguments) will result in a warning:

> 
> [1513092780631385996][pid: 19291][tid:139737018783488][ WARN]: This installation was built without support for setting a perf reference clock.
> [1513092780631422019][pid: 19291][tid:139737018783488][ WARN]: Any parameter to -k/--clockid will only affect the local reference clock.
> 

The warning should not appear, the respective options should not be available.

**Comment by phijor** [comment]
Since b13c7af the warning should only appear in a build with `USE_PERF_CLOCKID=OFF` if the user supplied a non-default argument to `--clockid`.

But as far as I remember there was a rationale for us to allow setting a local reference clock even though `use_clock_id` can't be used. So I would argue that these options should still be available with `USE_PERF_CLOCKID=OFF`.

**Comment by tilsche** [comment]
Sounds good
