### ISSUE TITLE
Handle cmd argument on lo2s -a

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#41]
If a command is passed `lo2s -a -- ./command`. The command is spawned and lo2s will record until it is finished - but not monitor it otherwise.

**Comment by cvonelm** [comment]
I now have tried to implement this using the current ProcessMonitor, disabling the code paths specific to monitoring, and came to the conclusion that the monitoring facilities of the ProcessMonitor and the ThreadMap are to deeply intertwined with the process control facilities to separate them in a simple manner.

I would now propose a new architecture for the ProcessMonitor which separates the monitoring and the process control contexts.

Here is a roughly overview of what i want to do:

1. Change the internal structure of the ThreadMap; The current ThreadMap is not fit for the task as it also allocates the ThreadMonitor and the ProcessInfos and some of its internal workings are currently dependent on the monitoring part(for example pid retrieval interacts with the ThreadMonitors).I would change the ```map<tid, ThreadMonitor>``` thread map we have currently to a ```map<pid, Process:{ProcessInfo, map<tid, Thread:{ThreadMonitor}>}>``` process map which mirrors the 2-level architecture
we are currently dealing with. The seemingly redundant ```Thread``` class is just there so that the ProcessController mustn't deal with the monitoring-dependent ThreadMonitor. For the new ProcessMap, both the ProcessInfo and the ThreadMonitor would be opaque objects which will be entirely managed by the ProcessMonitor

1. Split up the ProcessMonitor into a ProcessController and a ProcessMonitor, both will be given a reference to the same ProcessMap on construction:
     * ProcessController: This would contain the bulk of the current ProcessMonitor, and would be concerned with the raw managment of the process and all its childs using ptrace. If an event is relevant to the monitoring, the ProcessController calls the relevant callback in the ProcessMonitor. For example if a PTRACE_EVENT_FORK event would occur inside the ProcessController the ProcessController would add the Process and Thread objects for the pid using ProcessMap.insert() and then call monitor_.on_new_process(pid, Process &process) with the newly created Process object and its pid as the argument
     * ProcessMonitor: This class will inherit the monitoring part of the old ProcessMonitor and ThreadMap. It will consist of the different callbacks for the different events in the ProcessController, and will be a child of the MainMonitor class

Using this approach, we could implement the -a process mode using the ProcessController class and a DummyMonitor, where every callback does nothing. Another advantage that this approach might have is, that we can implement the "holy grail"(concurrent monitoring of both a process and the complete CPU) using a CPUProcessMonitor (and maybe a CPUThreadMonitor) class which just implements some of the callbacks differently to account for the dual monitoring mode

I would like some comments/critique on my design, before I implement it, to see if it is any sane, or if we want to try a different approach.
