### ISSUE TITLE
ref-cycles is only avail at kernel >= 3.3.0, but still default for metric-leader

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#44]
The default will fail for older kernels!
https://github.com/tud-zih-energy/lo2s/blob/791ca032eecba96bf8cd030b30782034bfdac032/src/config.cpp#L134

See also:
https://github.com/tud-zih-energy/lo2s/blob/2833c538fab33b2c61f293c144baa0055334e853/src/perf/event_provider.cpp#L62

**Comment by bmario** [comment]
Which metric can we use on older kernels instead?

**Comment by rschoene** [comment]
What about bus-cycles? That's been avail. from the beginning

**Comment by bmario** [comment]
With the same argument as in #1, I'd like to argue that checking a specific version number for the availability of the event isn't the solution. Also, I'm in favor of having a good default for reasonably new kernels instead of one, which works for all versions. To me, the resolution of this issue is more about documentation rather than changing code.

**Comment by rschoene** [comment]
I expect that when I build lo2s that it works with the default settings. Having a default that does not work on my system is annoying. We could use ref-cycles as soon as all active versions of SLES/RHEL support this, which is currently not the case. For now I'd favor ref-cycles for 3.3.0+ and bus-cycles for older kernels.
