### ISSUE TITLE
Add support for raw metrics

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#64]
In `perf`, I can pass raw metrics via the `-e` flag. This should also be supported by lo2s for `-e` and `-E`

Raw metrics are encoded in the following way `rNNNN`. More information is given in `man perf-list`

**Comment by cvonelm** [comment]
I have made a first implementation of this on the issue-64 branch. and tried it with lo2s -E r412e firestarter (r412e being the alias for the 'ram' event) and it produced results which where pretty much indistinguishable from using the 'ram' event directly, however before we go on, I would like to test this out on a more unorthodox setting(one where using a hexadecimal identifier is actually useful, because there is no human-readable identifier), is there a specific event and its hexadecimal identifier, which would be useful/interesting to test out on one of our test systems?

**Comment by bmario** [comment]
Fixed in 2c1514b2790b3f683f9dd4e4139d692748bbf137
