### ISSUE TITLE
Improve and centralize feature checks

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#86]
Move compile-time checks from source to cmake

**Comment by tilsche** [comment]
Does this refer to the LINUX_VERSION_CODE >= KERNEL_VERSION checks for available clocks_ in time.hpp? Are there any other?

**Comment by cvonelm** [comment]
Only other occurence that i've found is in perf/event_provider.cpp, but i wouldn't replace the LINUX_VERSION_CODE checks there with centralised cmake checks, but rather with checks like this: 
```c
// check if we can use alignment-faults
//#if LINUX_VERSION_CODE >= KERNEL_VERSION(2, 26, 3)
#ifdef PERF_COUNT_SW_ALIGNMENT_FAULTS 
```
Which should be more stable than LINUX_VERSION_CODE because of backporting etc. 

The rest of the #ifdef/#defined() etc. checks look ok to me
