### ISSUE TITLE
lo2s-latest trace symlink

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#95]
Often time one repeatedly runs lo2s and checks if the trace is good. This involves a lot of copying around trace names. A "lo2s-latest" symlink that keeps being update would be really nice.

I suggest making it a toggle argument, but on by default.

Name of the symlink and toggle argument are up for discussion.

**Comment by tilsche** [comment]
One issue with that is that the OTF2 archive is closed in `otf2::writer::archive::~archive`. This is a member of `lo2s::trace::Trace`, so we cannot just

**Comment by bmario** [comment]
What is wrong with: `ls | grep lo2s | tail -n 1`?

The issue I see is that what happens if there is a real trace with the same name as the link?

**Comment by tilsche** [comment]
> What is wrong with: ls | grep lo2s | tail -n 1?

You can't open and F5 that in Vampir. And yes, I tried it with symlinks.

> The issue I see is that what happens if there is a real trace with the same name as the link?

```
if (std::filesystem::symlink_status(latest_path).type == std::filesystem::file_type::symlink)
{
    std::filesystem::remove(latest_path);
    std::filesystem::create_symlink(latest_path, new_path);
}
```

**Comment by bmario** [comment]
I don't like that. Whatever the behavior of 🤷‍♂️ is, it will be surprising to users. Don't do that.
If you really want that behavior, then make a wrapper script. Haec, I can do it here:
```
#!/bin/sh
lo2s "$@"
if [ -L "lo2s-latest" ]; then
  rm -f lo2s-latest
fi
ln -s $(ls | grep lo2s | tail -n 1) lo2s-latest
```

**Comment by tilsche** [comment]
🤷 will almost never happen and probably just be a nice informative message. So that being surprising is not an argument.

**Comment by phijor** [comment]
While I like the idea of having a symlink pointing to the lastest trace generated, I have to agree with @bmario that implementing the logic in `lo2s` itself lends itself to surprising behavior.

Personally, I would prefer composability of small, independent tools over yet another feature that we'd have to maintain. Especially if it has to do with filesystems. So that's a :+1: from me for the wrapper script.

Indeed, one could even obtain the latest trace directory from `lo2s`' output itself:
```sh
#!/bin/sh
OUTPUT_DIR=$(lo2s "$@" | sed -n 's/^\[ lo2s:.*wrote.*iB \(.*\)\]$/\1/p')
if [ -L "lo2s-latest" ]; then
  rm -f lo2s-latest
fi
ln -s $OUTPUT_DIR lo2s-latest
```
I concede that this simply shifts the problem from having to maintain filesystem-related code to having to maintain regexes, but I guess the summary `lo2s` prints is not bound to change anytime soon.

**Comment by cvonelm** [comment]
What was the consensus again that we have reached in the last SHK Meeting?

**Comment by bmario** [comment]
The new consensus is to create the environment variable `LO2S_OUTPUT_LINK`, which determines the name of the link. If it is set, then create the link with the given name. If that link exists and is a symbolic link, then overwrite it, else create a warning. If the variable is not set, don't do anything.
